baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Docs Pax Facturacion'

[module]
    [[module.imports]]
        path = "lotusdocs-release"
        disable = false
    [[module.imports]]
        path = "github.com/twbs/bootstrap"
        disable = false
